// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI3mUtHBNnK3otYwrjRDafWLj9wqI6xEg',
    appId: '1:691732837478:web:22132c2a42587b3f7529a7',
    messagingSenderId: '691732837478',
    projectId: 'alter-2023',
    authDomain: 'alter-2023.firebaseapp.com',
    storageBucket: 'alter-2023.appspot.com',
    measurementId: 'G-699TYMP3TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2nBpUXjGd5WKijxuXfO5qGPL7qdQIp8',
    appId: '1:691732837478:android:f274c24ae7e52b3a7529a7',
    messagingSenderId: '691732837478',
    projectId: 'alter-2023',
    storageBucket: 'alter-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmJMurwTNuVEKr2SSCE-BjUWlzcjLwM3c',
    appId: '1:691732837478:ios:2f3d167e5d4400a57529a7',
    messagingSenderId: '691732837478',
    projectId: 'alter-2023',
    storageBucket: 'alter-2023.appspot.com',
    iosBundleId: 'com.example.alter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmJMurwTNuVEKr2SSCE-BjUWlzcjLwM3c',
    appId: '1:691732837478:ios:37977f82bebb5dbc7529a7',
    messagingSenderId: '691732837478',
    projectId: 'alter-2023',
    storageBucket: 'alter-2023.appspot.com',
    iosBundleId: 'com.example.alter.RunnerTests',
  );
}
